class UserState:
    START = "START"
    WAITING_NAME = "WAITING_NAME"           
    WAITING_ID_STENCIL = "WAITING_ID_STENCIL" 
    WAITING_RECEIPT = "WAITING_RECEIPT"
    WAITING_ADMIN = "WAITING_ADMIN"
    WAITING_FOR_BROADCAST = "WAITING_FOR_BROADCAST"
    WAITING_APPROVAL = "WAITING_APPROVAL" 